server:
  port: 80

spring:
  cloud:
    consul:
      host: 111.230.204.58
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: false
  application:
    name: cloud-consumer-order
